### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Yonee3** [SkyWtkh/RayNet#2]
help

**Comment by SkyWtkh** [comment]
try:
python3 ray or python3 "ray"

Remember to have python3 installed along with pip3 and a Linux distribution based on debian, the installer for the requirements will appear shortly

**Comment by Yonee3** [comment]
yess I've already run, but the method has low power

**Comment by Yonee3** [comment]
Good design, More updates plss

**Comment by SkyWtkh** [comment]
Thank you for supporting RayNet! version 2 will be out soon with: new method + 2 new tools + new user interface (UI)
for version 3 I plan to add more methods!
